name: Build and Deploy NuGet Package

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release --output ${{ github.workspace }}\Package

    - name: Find latest .nupkg file
      id: find-package
      run: |
        $latestPackage = Get-ChildItem -Path "${{ github.workspace }}\Package" -Filter *.nupkg | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        Write-Output "Latest package: $latestPackage"
        Write-Output "::set-output name=latest_package::$latestPackage"

    - name: Publish NuGet package
      run: dotnet nuget push ${{ steps.find-package.outputs.latest_package }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
