name: Build and Deploy NuGet Package

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release --output ./Package

    - name: Find latest .nupkg file
      id: find-package
      run: |
        latest_package=$(ls -t ${{ github.workspace }}\Package\*.nupkg | head -n 1)
        echo "::set-output name=latest_package::$latest_package"

    - name: Publish NuGet package
      run: dotnet nuget push ${{ steps.find-package.outputs.latest_package }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
