name: Build and Deploy NuGet Package

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Core
      run: dotnet build --configuration Release -project Core\Core.csproj

    - name: Pack Core
      run: dotnet pack --configuration Release --output ${{ github.workspace }}\Package\Core -project Core\Core.csproj

    - name: Build Core.Caching
      run: dotnet build --configuration Release -project Core.Caching\Core.Caching.csproj

    - name: Pack Core.Caching
      run: dotnet pack --configuration Release --output ${{ github.workspace }}\Package\Core.Caching -project Core.Caching\Core.Caching.csproj

    - name: Find latest .nupkg file
      id: find-package
      run: |
        $latestPackageCore = Get-ChildItem -Path "${{ github.workspace }}\Package\Core" -Filter *.nupkg | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        Write-Output "Latest package for Core: $latestPackageCore"
        Write-Output "::set-output name=latest_package_core::$latestPackageCore"
        $latestPackageCoreCaching = Get-ChildItem -Path "${{ github.workspace }}\Package\Core.Caching" -Filter *.nupkg | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        Write-Output "Latest package for Core.Caching: $latestPackageCoreCaching"
        Write-Output "::set-output name=latest_package_core_caching::$latestPackageCoreCaching"


